package:
  name: edgartools
  version: "3.3.1"

source:
  git_rev: c39a1c1eebc6d40a9f9982d18e341dd9eb958aa3
  git_url: https://github.com/dgunning/edgartools

requirements:
  build:
    - python
    - setuptools
    - httpx>=0.25.0
    - pandas>=2.0.0
    - tabulate>=0.9.0
    - pyarrow>=14.0.0
    - bs4>=4.10.0
    - lxml>=4.4
    - rich>=13.0.0
    - fastcore>=1.5.29
    - humanize>=4.0.0
    - tenacity==8.3.0
    - stamina>=24.2.0
    - orjson>=3.6.0
    - textdistance>=4.5.0
    - haystack-bm25>=1.0.0
    - rapidfuzz>=3.5.0
    - unidecode>=1.2.0
    - pydantic>=2.0.0
    - tqdm>=4.62.0
    - nest-asyncio>=1.5.1

  run:
    - python>=3.9

about:
  home: https://github.com/dgunning/edgartools
