site_name: edgartools
theme:
  name: "readthedocs"

nav:
  - Overview: index.md
  - Filtering: filtering-filings.md
  - Navigating: navigating-filings.md
  - Filings: working-with-filings.md
  - Companies: using-the-company-api.md
  - Attachments: attachments.md
  - Financials: company-financials.md
  - Data Objects: data-objects.md
  - eightk-filings.md
  - local-data.md
