site_name: edgartools
theme:
  name: "readthedocs"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

nav:
  - Overview: index.md
  - using-the-company-api.md
  - company-financials.md
  - data-objects.md
  - eightk-filings.md
  - local-data.md
