site_name: edgartools
theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

nav:
  - Overview: index.md
  - using-the-filings-api.md
  - using-the-company-api.md
  - parsing-filing-data.md
  - working-with-xbrl.md
  - eightk-filings.md
