site_name: edgartools
theme:
  name: "readthedocs"

nav:
  - Overview: index.md
  - Filtering: filtering-filings.md
  - Navigating: navigating-filings.md
  - Working with Filings: working-with-filings.md
  - using-the-company-api.md
  - Financials: company-financials.md
  - data-objects.md
  - eightk-filings.md
  - local-data.md
